TRAINING_CLICK_DELAY = 0.12
TRAINING_WAIT_DELAY = 0.10
TRAINING_RETRY_DELAY = 0.05
TRAINING_DETECTION_DELAY = 0.05

MENU_RETURN_DELAY = 0.10
MEDIC_CHECK_DELAY = 0.10

ENERGY_READ_RETRY_DELAY = 0.10

RACE_SEARCH_TIMEOUT = 30

MAX_TRAINING_RETRY = 5
MAX_DETECTION_ATTEMPTS = 2
